CREATE TABLE CRICKET_COUNTRIES(
COUNTRY_ID INT NOT NULL,
COUNTRY_NAME VARCHAR(50) NOT NULL,
PRIMARY KEY (COUNTRY_ID),
UNIQUE(COUNTRY_NAME)
);

CREATE TABLE TOURNAMENT_LIST(
TOURNAMENT_ID INT NOT NULL,
TOURNAMENT_NAME VARCHAR(200) NOT NULL,
COUNTRY_NAME VARCHAR(50) NOT NULL,
PRIMARY KEY (TOURNAMENT_ID),
FOREIGN KEY (COUNTRY_NAME) References CRICKET_COUNTRIES(COUNTRY_NAME)
);

INSERT INTO CRICKET_COUNTRIES (COUNTRY_ID,COUNTRY_NAME) VALUES 
(1,'England'),(2,'Australia'),(25,'Bangladesh'),(40,'Afghanistan'),(6,'India'),(29,'Ireland'),(5,'New Zealand'),(7,'Pakistan'),(3,'South Africa'),(8,'Sri Lanka'),(4,'West Indies'),(9,'Zimbabwe'),(19,'Hong Kong'),(20,'PNG'),(30,'Scotland'),(27,'UAE'),(37,'Oman'),(15,'Netherlands'),(17,'Canada'),(26,'Kenya'),(33,'Nepal'),(11,'USA');

INSERT INTO CRICKET_COUNTRIES (COUNTRY_ID,COUNTRY_NAME) VALUES (0,'Internationals'),(100,'Women')

CREATE TABLE CURRENT_SCORES(
MATCH_ID INT NOT NULL,
TEAM_ONE_SCORE VARCHAR(250),
TEAM_TWO_SCORE VARCHAR(250),
BATSMAN_ONE_NAME VARCHAR(250),
BATSMAN_TWO_NAME VARCHAR(250),
BATSMAN_ONE_SCORE VARCHAR(50),
BATSMAN_TWO_SCORE VARCHAR(50),
BATSMAN_ONE_BOUNDARIES VARCHAR(50),
BATSMAN_TWO_BOUNDARIES VARCHAR(50),
BATSMAN_ONE_SR FLOAT,
BATSMAN_TWO_SR FLOAT,
BOWLER_ONE_NAME VARCHAR(250),
BOWLER_TWO_NAME VARCHAR(250),
BOWLER_ONE_OVERS FLOAT,
BOWLER_TWO_OVERS FLOAT,
BOWLER_ONE_MAIDENS INT,
BOWLER_TWO_MAIDENS INT,
BOWLER_ONE_RUNS INT,
BOWLER_TWO_RUNS INT,
BOWLER_ONE_WICKETS INT,
BOWLER_TWO_WICKETS INT,
BOWLER_ONE_ECO FLOAT,
BOWLER_TWO_ECO FLOAT,
PRIMARY KEY (MATCH_ID),
FOREIGN KEY (MATCH_ID) References CURRENT_MATCHES(MATCH_ID)
)