CREATE TABLE CURRENT_MATCHES(
MATCH_ID INT NOT NULL,
TEAM_1 VARCHAR(50) NOT NULL,
TEAM_2 VARCHAR(50) NOT NULL,
MATCH_TYPE VARCHAR(50) NOT NULL,
MATCH_DETAILS VARCHAR(150) NOT NULL,
MATCH_URL VARCHAR(200) NOT NULL,
PRIMARY KEY (MATCH_ID)
);

ALTER TABLE CURRENT_MATCHES
MODIFY COLUMN MATCH_TYPE VARCHAR(200)