INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES ('England','MATADOR BBQS ONE-DAY CUP','Australia'),(2,'SHEFFIELD SHIELD','Australia'),(3,'BIG BASH LEAGUE','Australia')

INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (4,'MARYLEBONE CRICKET CLUB UNIVERSITY MATCHES',1),(5,'SPECSAVERS COUNTY CHAMPIONSHIP DIVISION ONE',1),(6,'SPECSAVERS COUNTY CHAMPIONSHIP DIVISION TWO',1),
(7,'ROYAL LONDON ONE-DAY CUP',1),(8,'NATWEST t20 BLAST',1),(9,'NORTH-SOUTH SERIES',1)

INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (10,'BANGLADESH CRICKET LEAGUE','Bangladesh'),(11,'BANGLADESH PREMIER LEAGUE','Bangladesh'),(12,'NATIONAL CRICKET LEAGUE','Bangladesh'),(13,'DHAKA PREMIER DIVISION','Bangladesh')


INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (14,'SHPAGEEZA CRICKET LEAGUE','Afghanistan'),(15,'AHMAD SHAH ABDALI 4-DAY TOURNAMENT','Afghanistan')

INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (16,'INDIAN PREMIER LEAGUE','India'),(17,'SYED MUSHTAQ ALI TROPHY ZONAL','India'),(18,'INTER STATE TWENTY-20','India'),(19,'DULEEP TROPHY','India'),
(20,'RANJI TROPHY','India'),(21,'IRANI TROPHY','India'),(22,'DEODHAR TROPHY','India'),(23,'VIJAY HAZARE TROPHY','India')

INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (24,'CRICKET IRELAND INTER-PROVINCIAL CHAMPIONSHIP','Ireland'),(25,'CRICKET IRELAND INTER-PROVINCIAL LIMITED OVER CUP','Ireland'),(26,'CRICKET IRELAND INTER-PROVINCIAL TWENTY20 TROPHY','Ireland')

INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (27,'PLUNKET SHIELD','New Zealand'),(28,'THE FORD TROPHY','New Zealand'),(29,'SUPER SMASH','New Zealand')

INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (30,'PAKISTAN SUPER LEAGUE','Pakistan'),(31,'PAKISTAN CUP','Pakistan'),
(32,'NATIONAL T20 CUP','Pakistan'),(33,'QUAID-E-AZAM TROPHY','Pakistan'),
(34,'PAKISTAN ONE DAY CUP','Pakistan'),(35,'DEPARTMENTAL ONE DAY CUP','Pakistan'),(36,'REGIONAL ONE DAY CUP','Pakistan')


INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (37,'SUNFOIL 3-DAY CUP','South Africa'),(38,'SUNFOIL SERIES','South Africa'),
(39,'AFRICA T20 CUP','South Africa'),(40,'CSA PROVINCIAL ONE-DAY CHALLENGE','South Africa'),
(41,'CSA T20 CHALLENGE','South Africa'),(42,'MOMENTUM ONE DAY CUP','South Africa')

INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (43,'PREMIER LEAGUE TOURNAMENT TIER A','Sri Lanka'),
(44,'PREMIER LEAGUE TOURNAMENT TIER B','Sri Lanka'),
(45,'DISTRICTS ONE DAY TOURNAMENT','Sri Lanka')


INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (46,'CARRIBEAN PREMIER LEAGUE','West Indies'),
(47,'WICB PROFESSIONAL CRICKET LEAGUE REGIONAL 4 DAY TOURNAMENT','West Indies'),
(48,'WEST INDIES CRICKET BOARD REGIONAL SUPER50','West Indies')

INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (49,'LOGAN CUP','Zimbabwe')

INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (50,'TEST MATCHES','Internationals'),
(51,'ONE-DAY INTERNATIONALS','Internationals'),(52,'TWENTY20 INTERNATIONALS','Internationals')

INSERT INTO TOURNAMENT_LIST(TOURNAMENT_ID,TOURNAMENT_NAME,COUNTRY_NAME) VALUES (53,"WOMEN'S ONE-DAY INTERNATIONALS",'Women')
